source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'rails', '~> 6.1'
    gem 'eventmachine', '~> 1.2.7', platforms: :ruby
    gem 'makeconf', '~> 0.2.0'
    gem 'racc', '~> 1.4', '>= 1.4.14'
    gem 'nio4r', '~> 2.5', '>= 2.5.8'
    gem 'fast-stemmer', '~> 1.0', '>= 1.0.2'
    gem 'http_parser.rb', '~> 0.8.0'
    gem 'json', '~> 2.7', '>= 2.7.3'
    gem 'rubocop', '~> 1.44.0'
    gem 'mini_racer'
    gem 'update'
    gem 'libv8-node'
    gem 'classifier-reborn'
    gem 'jekyll-archives'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-regex-replace'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-tabs'
    gem 'jekyll-toc'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'unicode_utils'
    gem 'webrick'
end
group :other_plugins do
    gem 'css_parser'
    gem 'feedjira'
    gem 'httparty'
end
